# Acerca de los autores {#author .unnumbered}

Cada libro de AOSCD está a cargo de un equipo en particular, miembros de la comunidad, aunque cualquiera que esté interesado puede aportar al desarrollo del libro. Vea [como contribuir](https://github.com/AOSCD/aoscd-matlab#contribuyendo).

A continuación se muestra un listado de las personas que han contribuido con este libro en particular:<br/>

```{r, results = "asis", echo = FALSE, message = FALSE}
library(dplyr)
contributors <- readr::read_csv("contributors.csv", col_types = list())
contributors <- contributors %>% 
  mutate(
    link = glue::glue("[\\@{login}](https://github.com/{login})"),
    desc = ifelse(is.na(name), link, glue::glue("{name} ({link})"))
  )
cat(paste0(contributors$desc, collapse = ", "))
```

## Daniel E. de la Rosa {-}

Daniel E. de la Rosa (https://delarosadaniel.com) es el creador de AOSCD (https://aoscd.github.io/). Es economista en Grupo de Consultoría Pareto (https://gcpareto.com). Economista de profesión con estudios de posgrado en Matemáticas Puras y Maestría en Ciencia de los Datos.

Es autor de varios paquetes en el ecosistema R, tales como __Rmdx__ (https://drdsdaniel.github.io/Rmdx/), __Dmisc__ (https://drdsdaniel.github.io/Dmisc/) y __crender__ (https://drdsdaniel.github.io/crender/). Creador del proyecto **En**cuestas **Dom**inicanas **e**n **R** (endomer) (https://endomer.github.io/). Es cofundador de la compañía DBRA Solutions (https://dbra.com.do/).

No es de redes sociales, pero si en alguna lo has de encontrar es en Twitter (https://twitter.com/drdsdaniel) o, por supuesto, en GitHub (https://github.com/drdsdaniel/) colaborando en alguno que otro proyecto Open Source.

<!-- ## Anthony Mora {-} -->

<!-- ## Deyanara Matos {-}  -->
