# Sintaxis

Esta capítulo reune los aspectos de sintaxis de todos los lenguajes utilizados a lo largo del libro. Elementos como la inserción de comentarios, la creación de objetos básicos, entre otros que sean prácticamente común a cualquier implementación del lenguaje.

## Secciones de código

### MatLab

En MatLab se crea una sección de código insertando dos signos de porcentaje `%%`, y una subsección insertando tres `%%%`.

### R

En R para insertar una sección código inicias la línea de código con un signo de número `#` y la terminas con cuatro signos de `#` o guiones `-`.

Ejemplo:

\# Sección 1 ----

## Comentarios

Los comentarios en los lenguajes de programación representan texto legible que sirve para orientar al programador pero que en principio son obviados por el lenguaje. Por lo general son utilizados para describir el código a su alrededor.

### MatLab

En MatLab un comentario se inserta utilizando el signo de porcentaje **`%`**.

### R

En un script básico de R, un comentario puede ser insertado utilizando el símbolo de número **`#`**.

### Python

En Python los comentarios también se insertan utilizando el signo de número **`#`**.

### Octave

En octave mientras tanto, la inserción de un comentario se puede realizar utilizando cualquiera de los dos signos **`#`** o **`%`**.
